/*
* generated by Xtext
*/
package org.vclipse.dependency.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DependencyOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
