/*
* generated by Xtext
*/
package org.vclipse.vcml.ui.contentassist;

import org.vclipse.vcml.ui.contentassist.AbstractDependencyProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DependencyProposalProvider extends AbstractDependencyProposalProvider {

}
