/*
 * generated by Xtext
 */
package org.vclipse.procedure;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProcedureRuntimeModule extends org.vclipse.procedure.AbstractProcedureRuntimeModule {

}
