/*
* generated by Xtext
*/
package org.vclipse.vcml.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class ProcedureDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
	
}
