/*
 * generated by Xtext
 */
package org.vclipse.vcml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DependencyUiModule extends org.vclipse.vcml.ui.AbstractDependencyUiModule {
	public DependencyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
