/*
 * generated by Xtext
 */
package org.vclipse.vcml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProcedureUiModule extends org.vclipse.vcml.ui.AbstractProcedureUiModule {
	public ProcedureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
