/*
 * generated by Xtext
 */
package org.vclipse.vcml;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.vclipse.vcml.conversion.VCMLValueConverter;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConditionRuntimeModule extends org.vclipse.vcml.AbstractConditionRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return VCMLValueConverter.class;
	}

}
