/*
 * generated by Xtext
 */
package org.vclipse.vcml;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConstraintRuntimeModule extends org.vclipse.vcml.AbstractConstraintRuntimeModule {

}
