/*
 * generated by Xtext
 */
package org.vclipse.vcml;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProcedureRuntimeModule extends org.vclipse.vcml.AbstractProcedureRuntimeModule {

}
