/*
 * generated by Xtext
 */
package org.vclipse.constraint.scoping;

import org.vclipse.dependency.scoping.DependencyScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ConstraintScopeProvider extends DependencyScopeProvider {

}
