/*
 * generated by Xtext
 */
package org.vclipse.constraint;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConstraintRuntimeModule extends org.vclipse.constraint.AbstractConstraintRuntimeModule {

}
