/*
 * generated by Xtext
 */
package org.vclipse.dependency;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DependencyRuntimeModule extends org.vclipse.dependency.AbstractDependencyRuntimeModule {

}
