/*
 * generated by Xtext
 */
package org.vclipse.condition;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConditionRuntimeModule extends org.vclipse.condition.AbstractConditionRuntimeModule {

}
